[phases.setup]

nixPkgs = ['python310']

[phases.install]
cmds = [
	'python3 -m ensurepip --upgrade',
	'python3 -m pip install --upgrade pip',
	'pip3 install -r backend/requirements.txt'
]

[phases.build]
cmds = ['echo "Build completed for backend"']

[start]
cmd = 'python backend/get_chats.py'