[phases.setup]

nixPkgs = ['python310']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['echo "Build completed for backend"']

[start]
cmd = 'python backend/get_chats.py'