[phases.setup]
nixPkgs = [
	'python310',
	'python310Packages.pip',
	'python310Packages.telethon',
	'python310Packages.python-dotenv'
]

[phases.install]
cmds = []

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python telegram_parser.py'