[phases.setup]
nixPkgs = ['python310']

[phases.install]
cmds = [
	'python3 -m ensurepip --upgrade',
	'python3 -m pip install --upgrade pip',
	'pip3 install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python telegram_parser.py'